### ISSUE TITLE
Business account "list" command

### ISSUE THREAD

**Issue by castaway** [carpii/barclayscrape#1]
Hey..

I think I may have messed up some of my business account detail extracting.. I used "list" the other day to test the merged branches, and now I'm unsure what its supposed to display.

I get:
```
┌─────────┬──────────────────┬──────────────────┬─────────────┬──────────┐
│ (index) │        0         │        1         │      2      │    3     │
├─────────┼──────────────────┼──────────────────┼─────────────┼──────────┤
│    0    │ '<sortcode+accno>' │ '<sortcode+accno>' │ 'COMMUNITY' │ '<largish number>' │
└─────────┴──────────────────┴──────────────────┴─────────────┴──────────┘
```

What're those fields supposed to be? are the columns supposed to have titles? (If not could we add em?)

The last one could be balance, if so its in pence or parts of pence ;)

**Comment by carpii** [comment]
It's not a feature I've ever used, so I don't know what the fields are intended to be 

I do recall the column headings were always just integers though. I'll do a bit of work on it when I find time.

**Comment by carpii** [comment]
Latest push fixes the parsing of account balances (your recent changes were stripping out `-` and also `.`)

The `list` columns are Barclays sortcode+account, Optional alias (in Barclayscrape config), Label (the account name from Barclays), account balance

Latest site changes has some issues though, in that it will only show the first three accounts. There's some site interaction I need to code to get the full list, but it's proving a bit tricky so far

**Comment by carpii** [comment]
@castaway could you check out the `account_list` branch, to make sure the `list` feature still works for you?

I had to jump through a few hoops to get it working on my account 
- will now reveal all accounts, if you have more than 3
- had to add a bunch more error checking to ensure non-standard accounts like mortgage or Rewards, dont generate javascript exception
- Have also added column headings to the console list output

**Comment by castaway** [comment]
> Latest push fixes the parsing of account balances (your recent changes were stripping out `-` and also `.`)
> 
> The `list` columns are Barclays sortcode+account, Optional alias (in Barclayscrape config), Label (the account name from Barclays), account balance
> 
> Latest site changes has some issues though, in that it will only show the first three accounts. There's some site interaction I need to code to get the full list, but it's proving a bit tricky so far

I needed em stripped for the eventual name of the ofx to be "correct" (tho if it happens elsewhere, all good) .. will test

**Comment by castaway** [comment]
Sadly: ```Couldn't find selector "#showAllButton button" on page https://bank.barclays.co.uk/olb/balances/digital/btr/home/business. Screenshot saved to error.png``` - checking the image, I don't see any show all button, or anything that looks like one (we have exactly one account)

**Comment by carpii** [comment]
> Sadly: `Couldn't find selector "#showAllButton button" on page 

Ahh, of course, It's not even appearing for you with one account

Please pull and try again, hopefully fixed

**Comment by carpii** [comment]
> I needed em stripped for the eventual name of the ofx to be "correct" (tho if it happens elsewhere, all good) .. will test

The stripping I mentioned only refers to the account balance. It should not affect OFX filename

**Comment by castaway** [comment]
ahh that works ..
acc_no and alias are the same string, both ```<sortcode><accnum>``` all jammed together. balance looks saner now

**Comment by carpii** [comment]
Ok, thanks. I'll merge into master

> acc_no and alias are the same string

The alias is coming from barclayscrape config. You can assign a 'friendly name' based on sortcode+account number

I'll remove the alias feature at some point, just to simplify the code. I don't think it's useful anymore
