### ISSUE TITLE
Output balance to csv?

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [carpii/barclayscrape#2]
I would like to inquire if there is a possibility to generate a CSV file for the balance instead of a list of the transactions. I appreciate the effort you put into maintaining this.

I did try to output the list to a json file with:

```
node barclayscrape.js --plogin list --json
``` 

I did also try it with a path but it only outputs the list in the terminal and doesn't generate a file. 

Thank you for your time and consideration.

**Comment by carpii** [comment]
You should be able to dump the json to a file using standard redirection (rather than passing a file path to barclayscrape)...

    node barclayscrape.js --plogin list --json > list.json

You can also pipe it directly into `jq` and transform it into a csv...

    node barclayscrape.js --plogin list --json | jq -r '(map(keys) | add | unique) as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv' > list.csv

I'd probably do this in two stages though, so you can check the json was downloaded properly

**Comment by My-Name-Is-Adam** [comment]
Thanks for your help! 

I've managed to come up with a similar solution that does the job - in case anyone is reading this and wondering what then I did the following:

```
node barclayscrape.js --plogin list >> output.csv
``` 

Then I used the following to get just the balance:

```
Get-Content -Path output.csv | Select-Object -Skip 3 -First 1 | ForEach-Object {$_ -replace '^.*''([^'']*)''.*$', '$1' | Out-File output_bal.csv}
``` 

Thanks again! 💯
