### ISSUE TITLE
Unknown window - browser issue (quick fix please!)

### ISSUE THREAD

**Issue by 007-JB** [carpii/barclayscrape#4]
![error](https://github.com/carpii/barclayscrape/assets/13701124/4ae9f096-1c5e-4c65-9146-e5fc849ad7a6)

Hi - I love this program please can you assist with this it should be a quick fix I suspect - would save me hours going through and trying to understand where to fix with browser or clicking the relevant button and continuing...

**Comment by carpii** [comment]
Hi, I've seen this error crop up a couple of times in the past, but I have not been able to debug it as it seems to only show once then disappear

Can you provide the full commandline you are using (excluding any sensitive info)

Along with the output of..

`npm ilst puppeteer`

and

`node -v`

**Comment by 007-JB** [comment]
Hiya


Quick response thanks.
Yeah I am busy driving now. I’ll try to replicate when I get to the
destination.
I suspect debugging will involve you being able to replicate and
understanding what the elements of that screen are.
I was hoping there will be some kind of select star statement to Get all
the elements on that page and click the appropriate box but again you
wouldn't be to test without replicating that page.


I’m pretty sure there is a “browser visible” option - perhaps I can change
to get to that page myself - then figure out what elements need to be
selected and ask you where that code should be placed?

Otherwise will send back info you asked for shortly.


 Cheers

**Comment by 007-JB** [comment]
yep, everytime....

<img width="457" alt="image" src="https://github.com/carpii/barclayscrape/assets/13701124/b378b5ae-5e62-4a38-be57-38be8e374c80">

**Comment by 007-JB** [comment]
yep every time - I'm getting this 
<img width="452" alt="barclays" src="https://github.com/carpii/barclayscrape/assets/13701124/2b902810-147e-4426-840a-df50ac078b76">
same error mate.. can you help?

I used 'list' instead of 'ilst' as you had it - former worked, latter didn't recognise code... output:

<img width="304" alt="image" src="https://github.com/carpii/barclayscrape/assets/13701124/d52a8534-d992-4b78-938d-db36b841d855">

<img width="74" alt="image" src="https://github.com/carpii/barclayscrape/assets/13701124/5c353688-9b5d-47e1-af11-9b663a89aa0a">

**Comment by carpii** [comment]
maybe you;ve installed puppeteer package globally. What does this show?

`npm list puppeteer -g`

**Comment by carpii** [comment]
in `session.js` try changing...

```
async loginStage1(credentials) {
    // Stage 1 of login - enter surname and membership number.
```

to this (insert 2 lines)

```
async loginStage1(credentials) {
    await u.dump_to(this.page, "./dump");
    process.exit(1);
    // Stage 1 of login - enter surname and membership number.
```

then run barclayscrape. It will exit quickly, and save a dump.html

Open dump.html a text editor (not browser) and then search for "Browser alert". 
I suspect it won't be present, but if its there it would make a fix much easier

**Comment by 007-JB** [comment]
> maybe you;ve installed puppeteer package globally. What does this show?
> 
> `npm list puppeteer -g`

<img width="244" alt="image" src="https://github.com/carpii/barclayscrape/assets/13701124/7c000e91-0ae0-4f58-9eb8-b1bd664b2788">

**Comment by carpii** [comment]
the version of Chrome which barclayscraper uses is directly tied to puppeteer version, and yours is quite out of date

You could try updating your global packages (from barclayscrape directory)

```
npm update -g
```

or remove the global package and install puppeteer as a local package (again from barclayscrape directory)

```
npm uninstall -g puppeteer
npm install
```

**Comment by carpii** [comment]
I rolled back to puppeteer 13, and was able to reproduce the problem 

I've written code to detect and bypass the browser warning.. however if the warning is NOT present (as in most cases), it can add anywhere from a 10-30 seconds delay to the scraper 

I think I'll scrap this detection code, and just suggest upgrading puppeteer as the only recommended solution for now.

**Comment by 007-JB** [comment]
Hiya -
Can close this as I simply used `this.browser = await puppeteer.launch(options,{ executablePath=..}):` with path to a suitable chrome.exe file (version it was using is 101 or something, worth updating but not sure if this is due to my npm puppeteer or what - although tried updating puppeteer several different ways - none of this worked except above.

Now it's stuck on not being able to find accounts.body i.e. `await u.wait(this.page, '.accounts-body')` -- so presume the main page is different to the one you raised but trying alternative solutions to scrape - nice log in feature though not sure how to combine headless = false with above {executablePath=}.

One for a separate issue to raise when I can.

**Comment by carpii** [comment]
I'd really try to find a way to uninstall the old global puppeteer if you can, otherwise you are building future problems into it (which I'll be unable to support)

What was the issue with below?

cd into your barclayscrape dir then...
```
npm uninstall -g puppeteer
git pull
npm install
```

the `git pull` is important as the `.accounts-body` issue suggests you are using a much older version of barclayscrape too

---

Finally, in your barclaysscrape dir, run this...
`grep 'russss' .git/config`

if this shows any output, it suggests your git repo is still pointing at the old discontinued repo (instead of mine)
